# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-20 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
