# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-24 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20180324_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_desc',
            new_name='course_des',
        ),
    ]
