# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-25 10:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20180324_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_des',
            new_name='course_desc',
        ),
    ]
